### ISSUE TITLE
get original process output colors

### ISSUE THREAD

**Issue by devmondo** [appium/node-teen_process#26]
Hi, this is really working great, but i got one issue, the output i get from the running process when i use below or any of the events is always in white, even though the process itself if I run it in standalone produces colorful output, maybe i am missing something?

also can we get rid of [stdout] prefix? 

thanks in advanced. 

```js
  proc.on("stream-line", line => {
            outputMessage(line , socketsManger);
    });
```

![image](https://user-images.githubusercontent.com/1266367/39304647-65c1801e-496b-11e8-8fb3-9144331a6e9f.png)

**Comment by jlipps** [comment]
FWIW I think the color issue has nothing to do with this package and to do with the way coloring in the terminal works. If a process detects that it's not being run in an interactive shell it often disables color output. You might be able to set some combination of environment variables like `TERM` and so on to get it to work? I forget, but I remember running into this problem before.

**Comment by devmondo** [comment]
thanks for the prompt reply, honestly nothing worked, could this help shed some light?
https://github.com/kimmobrunfeldt/concurrently/issues/8

**Comment by jlipps** [comment]
Yeah I don't think `stdio: inherit` will work because that attaches the subprocess streams to the global `process.stdout` et al. that means it won't be captured in the object returned to spawn.

one experiment could be to turn on `stdio: inherit` and then listen to `process.stdout` rather than the stdout pipe on the spawn object. does that work?

**Comment by devmondo** [comment]
thank you for the support,

you are right, with `inherit` the output is delegated to the global process and this is not the behavior i want. so i did what you advised and added this 
```js
  process.stdout.on(`data`,(buffer)=>{
        console.log(buffer);
    })
  ```

but unfortunately nothing is captured here, the colored output is still out of my control.

**Comment by devmondo** [comment]
for me and future users, I finally found it! `env.FORCE_COLOR = true;`  and no need to set `stdio:"inherit"`
we could make it as an option or add it to docs.
you can close this now, thank you very much for your time :)

**Comment by jlipps** [comment]
@devmondo good find. is this workaround general, or does it apply only to the particular process you're running?
