### ISSUE TITLE
process didn't end after 10000 ms

### ISSUE THREAD

**Issue by devmondo** [appium/node-teen_process#27]
hi, 
Maybe i am doing something wrong, but if i use `proc.stop()` and restart the process again, i get that error. i think it is done here https://github.com/appium/node-teen_process/blob/fef40185b2c29e5402acb9952bf3916dbfde815d/lib/subprocess.js#L189

but if i use `proc.proc.kill()`  this issue goes away. i am on windows os by the way.

**Comment by jlipps** [comment]
please share your code so we can take a look

**Comment by devmondo** [comment]
thank you for the reply, there you go 

```js
export async function customProcess() {
    let log: string = ``;
    const env = Object.create(process.env);
    env.FORCE_COLOR = true;
    const proc = new SubProcess(`my custom bin tool path`, [], {
        env,
        shell: true,
        stdio: `pipe`,
        detached: false
    });

    proc.on("exit", (code, signal) => {
        log = `process exited with code ${code} from signal ${signal}`;
        outputMessage(log, session.socket);
    });

    proc.on("stop", (code, signal) => {
        log = `process stoped - ${code} - ${signal}`;
        outputMessage(log, session.socket);
    });

    proc.on("end", (code, signal) => {
        log = `process ended - ${code} - ${signal}`;
        outputMessage(log, session.socket);
    });

    proc.on("die", (code, signal) => {
        log = `process died - ${code} - ${signal}`;
        outputMessage(log, session.socket);
    });

    proc.on("stream-line", line => {
        log = line;
        outputMessage(log, session.socket);
    });

    await proc.start();
}
```

then later in my app
```js
const myProcess = await customProcess();
myprocess.stop();
```
and then i might repeat the above  every 10 seconds (just example).

**Comment by jlipps** [comment]
1. i don't see you returning anything from `customProcess`, so how can you then call `stop` on it?
2. `SubProcess.stop` is an async function and should be awaited

**Comment by devmondo** [comment]
sorry what I posted is not correct code, and I do have it as you advised, but I still get this error, maybe it is a windows OS issue?

also does `teen_process` handle tree process disposal? if not, I think it is still a good idea for me to use `tree-kill` package to handle that correctly?

**Comment by jlipps** [comment]
hmm, I'm not sure then. We're just calling the library methods on the object returned from `spawn`. If more is required, then I guess maybe you do need another package? How would you kill this process just using vanilla Node, for example?

**Comment by devmondo** [comment]
I am not sure I understood what you mean but as I mention, I use `tree-kill` npm package as people recommend it for such situations and use the following code.
```js
 kill(myProcess.proc.pid, `SIGKILL`, (err: Error) => {
                                if (err) throw err;
                                // continue my business
                            });
```

I will  close the issue so I won't pollute the repo and I will keep investigating if it is not an issue on my side

**Comment by aral** [comment]
If your process starts another process (e.g., I have a process manager that starts a web server), then `proc.stop()` will not work and you have to, as @devmondo mentioned, use the `tree-kill` module instead. There is also a `tree-kill-promises` module so you can do:

```js
await kill(proc.pid)
```

If node-teen-process were to use tree-kill internally, it would avoid this edge case.

(Thanks @devmondo for your post, it helped. And thank you, @jlipps for this lovely little module.) :)
